### ISSUE TITLE
Do CCEval really works?

### ISSUE THREAD

**Issue by bigbrother001** [bronyayang/HallE_Control#2]
This paper is very comprehensive and inspiring, however, I have some questions.

The paper said that there is "a bias towards VQA-based evaluations might result in an incomplete assessment of detailed captions, which requires obtaining a comprehensive view of visual details", could you explain in more detail what are the drawbacks of the VQA-based approachs? And how to prove that CCEval is a better hallucination detector than CHAIR?

Looking forward to your reply.

**Comment by bronyayang** [comment]
Thanks for your interest to our paper!

> "a bias towards VQA-based evaluations might result in an incomplete assessment of detailed captions, which requires obtaining a comprehensive view of visual details" - explain in more detail what are the drawbacks of the VQA-based approaches

This means that evaluating on VQA cannot reflect the model performance on detailed caption tasks. Specifically, we observed this two bias:

1. Difference between (open-source) model behavior on VQA and detailed caption tasks: If you get a somehow complex scene, first prompt the model with outputting a detailed caption, then prompt the model with each object it mentioned in caption in VQA format, you will see some inconsistency of the model answer. Just a demonstrating example:

Detailed caption: "The picture shows (object 1) holding a (object 2) and (object 3) trying to eat (object 4). There are many (object 5) in the scene with (object 6). (object 7) is flying far away. ..."

VQA: Q: Is there a (object 1)? A: Yes. Q: Is there a (object 2)? A: Yes. Q: Is there a (object 3)? A: No. [Inconsistency] Q: Is there a (object x that is not in the detailed caption)? A: Yes. [Inconsistency]

This behavior is quantitatively demonstrated in Table 1 and Table 2: models have different rankings on VQA based benchmark, POPE and MME, and detailed caption based benchmark, CHAIR. Given these benchmark are on the same dataset MSCOCO, the models must have this inconsistent issue if they are in different ranking, otherwise the best model in POPE should be the best in CHAIR. This inconsistency makes the detailed caption hallucination unable to be detected by VQA evaluations alone.

2. Question answer bias: If you shuffle the answer given to the model: A. Apple, B. Bird, C. Cat, D. Dog --> A. Dog, B. Cat, C. Bird, D. Apple, the model may answer wrong... This experiment is not in the paper but we conduct it internally. Also, some model tend to answer Yes. This is shown in every Table with VQA bench (refer to Yes % column).

This bias is the explicit drawback of VQA. Due to some models not appropriately trained, the format that VQA bench requires is another burden to the model other than the task itself. Detailed caption task is more free form, so this is less burden for the model.

> How to prove that CCEval is a better hallucination detector than CHAIR?

CHAIR first pre-set the ground truth objects for an image, then it hard code matches the ground truth objects to the objects mentioned in the caption. This creates two issues:

1. The matching is too hard code: CHAIR uses wordnet to match GT and caption objects, so it can only detect singular or plural form of the words. This fails in this case for example: Caption: "There are little cats in the picture." GT: "kitten", or many other cases. CCEval suggest that this word matching to be done by GPT4, which is a more flexible and accurate synonym detector.
2. If caption mentions more detailed caption than GT, CHAIR will score the caption with low score without indicating the cause. CCEval added the metric to indicate number of object in the caption and length of the sentence. This can tell you if a low score is really due to the model failure or your model is just like to say a lot.

We want to emphasize that CCEval is a suggested evaluation pipeline/method for detailed caption, instead of a fixed benchmark. This method can be adapt to other datasets, models, and GPT4 prompt should be adjusted as it evolves (but needs to rerun your other baselines). We believe that the flexibility of CCEval is what get improved over CHAIR.
